version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      patch-upgrades:
        update-types: ["patch"]
      dev-upgrades:
        dependency-type: "development"
        update-types: ["minor"]
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    labels:
      - dependencies
